### PR TITLE
Bug/responsiveness

### PR DESCRIPTION
**Pull request by Joshuafolorunsho**
Work on responsiveness.

Mobile device - 375px

Before: 
image

After: 
image

Tablet device - 768px

Before:
image

After: 
image

### Self Check(Tick After Making pull Request)

- [ ✔] This issue was assigned to me
- [✔]  One Change in one Pull Request
- [ ✔] My file is in proper folder
- [✔]  ] I am following clean code and Documentation.
- [ ] I have added README.md with my script

### CODE REVIEW

**Comment by BALaka-18** [comment]
@Joshuafolorunsho there's another page too, didn't you work on it, just asking because I saw you made changes to ```index.html``` and not ```link_added.html```.

**Comment by Joshuafolorunsho** [comment]
> 
> 
> @Joshuafolorunsho there's another page too, didn't you work on it, just asking because I saw you made changes to `index.html` and not `link_added.html`.

Oh! Wasn't aware

**Comment by Joshuafolorunsho** [comment]
Will you merge this? Then after, I will go ahead and work on the other one or you I should work on it and push again?

**Comment by BALaka-18** [comment]
> Will you merge this? Then after, I will go ahead and work on the other one or you I should work on it and push again?

Alright. This looks good enough to merge.

**Review by BALaka-18 — APPROVED** [review]

**Pull request merged**
