### PR TITLE
Added Codecov github action

### PR DESCRIPTION
**Pull request by mdb571**
### What have you Changed -
Added [codecov](https://codecov.io) github action to the main workflow file
### Issue no.(must) -
#2 

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me
- [x] One Change in one Pull Request
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.
- [ ] I have added README.md with my script

### CODE REVIEW

**Comment by BALaka-18** [comment]
@mdb571 Please pull the recent changes and commit again. There seems to be some conflict probably due the changes we currently made. Thanks.

**Review by rexdivakar — CHANGES_REQUESTED** [review]
Pls fork the repo with the updated GitHub actions templates and add ur changes.

**Comment by mdb571** [comment]
@rexdivakar  there are no changes detected in the current master comparing to my fork.The workflow for my PR fails since I dont have the Discord Webhook secret in my repo.Please merge and see if the action builds successfully

**Review by rexdivakar — CHANGES_REQUESTED** [review]
Hey buddy, i have reviewed it and we need some corrections, please move the code block above the build status check conditions and apply for review.

image

**Comment by mdb571** [comment]
I have added a basic test file in order for the code coverage action to generate reports.You can later add more tests as the project advances.Here's my screenshot of the report generated by the action.Please review and suggest changes if required.
Screenshot_2020-10-02 Open-Dev-Community URL-Shortener

**Review by rexdivakar — APPROVED** [review]
Everything looks good, will approve it

**Comment by rexdivakar** [comment]
Great job buddy @mdb571

**Comment by mdb571** [comment]
Thanks 🚀

**Pull request merged**
